import clsx from "clsx";
import type { Metadata } from "next";

import Header from "@/components/header";
import { fontMono, fontSans, geistMono, geistSans } from "@/config/fonts";

import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark" style={{ colorScheme: "dark" }}>
      <body className={clsx(fontSans.variable, fontMono.variable, "antialiased")}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
